Committing batch and schedule class Assignment
Vardhman-Fexle-Trainee/Vardhman-Asiignmemts-Deploy pull request #20
Opened 2024-12-18 11:57 UTC by Vardhman-Fexle-Trainee

2024-12-18 12:34 UTC, shubhamAgarwal242 requested changes

2024-12-18 12:34 UTC, shubhamAgarwal242 commented on classes/LeadProcessorTest.cls
> +public with sharing class LeadProcessorTest {
@Vardhman-Fexle-Trainee, why you have added with sharing here?

2024-12-18 12:34 UTC, shubhamAgarwal242 commented on classes/LeadProcessor.cls
> +        return Database.getQueryLocator('SELECT Id, LeadSource FROM Lead' );
@Vardhman-Fexle-Trainee, we should add the check for LeadSource != 'Dreamforce' in this query after that we can remove the check from execute method

2024-12-18 12:34 UTC, shubhamAgarwal242 commented on classes/LeadProcessorTest.cls
> +        System.debug(leadList.size());
@Vardhman-Fexle-Trainee, Remove the debugs, Any debug should not deploy to production

2024-12-18 12:34 UTC, shubhamAgarwal242 commented on classes/LeadProcessorTest.cls
> +        System.assertEquals(200, leadList.size(), 'List is not returning 200 records') ;
@Vardhman-Fexle-Trainee, Please user Asser class intead of system.assertEquals

2024-12-18 13:01 UTC, Vardhman-Fexle-Trainee commented on classes/LeadProcessorTest.cls
> +public with sharing class LeadProcessorTest {
As it is added by Vs code by default and I forgot to change it.
Right now I am removing it.

2024-12-18 13:03 UTC, Vardhman-Fexle-Trainee commented on classes/LeadProcessorTest.cls
> +        System.assertEquals(200, leadList.size(), 'List is not returning 200 records') ;
Sure, I will add assert class method here.

2024-12-18 13:03 UTC, Vardhman-Fexle-Trainee commented on classes/LeadProcessorTest.cls
> +        System.debug(leadList.size());
Okay, I will remove it.

2024-12-18 13:03 UTC, Vardhman-Fexle-Trainee commented on classes/LeadProcessor.cls
> +        return Database.getQueryLocator('SELECT Id, LeadSource FROM Lead' );
Okay, so I have to use where clause.

2024-12-23 13:23 UTC, shubhamAgarwal242 approved these changes

2024-12-23 13:25 UTC, merged